### ISSUE TITLE
Some suggested updates to Assignment 1

### ISSUE THREAD

**Issue by NatalieBiderman** [monicathieu/cu-psych-1490#4]
Hi there, 
Here are some suggestions to improve assignment 1, given the addition of tidyverse package. 

- For the question "Does summary() tell you the data types of the columns in a dataframe?" we should write Yes instead of No.
- Same for the question "Does head() tell you the data types of the columns in a dataframe?"
- We should change class types examples from (interval, factor and numeric) to numeric and character. 
- Re: "Call summary() on a FACTOR column in IntroSurvey and inspect the output." - There isn't a factor variable in the data. Perhaps switch to asking summary of character columns. 
- Note that it didn't allow me to skip() the FACTOR question for some reason, when writing skip() it gave me the answer of the previous question about age column. 
- In: "Look at the full contents of the age column of IntroSurvey in console to see if | there is missing data in the column" - perhaps give them the code that enables to see the contents (IntroSurvey$age), in case they forgot how. 
- When asking them to compute mean with na.rm=TRUE, we can add na.rm=1 and na.rm=T as other possible answers. This also applies to the question regarding psychology courses taken by the students (mean(IntroSurvey$psych_courses, na.rm=TRUE)).
- Not sure what is the column that can answer this question: "What is the mean number of psychology classes taken by our participants?"
- Not sure students will be able to answer this question: "Enter a command that tells you how many participants are left-handed". Perhaps we can divide this to two stages, first tell them to write up the logical statement, and then tell them to add sum() before the statement to count the number of TRUE instances. 

Merci beaucoup,
Natalie

**Comment by monicathieu** [comment]
Copying questions below as to-do list format:

* [x] For the question "Does summary() tell you the data types of the columns in a dataframe?" we should write Yes instead of No.
* [x] Same for the question "Does head() tell you the data types of the columns in a dataframe?"
* [x] We should change class types examples from (interval, factor and numeric) to numeric and character.
* [x] Re: "Call summary() on a FACTOR column in IntroSurvey and inspect the output." - There isn't a factor variable in the data. Perhaps switch to asking summary of character columns. Note that it didn't allow me to skip() the FACTOR question for some reason, when writing skip() it gave me the answer of the previous question about age column. 
* [x] In: "Look at the full contents of the age column of IntroSurvey in console to see if | there is missing data in the column" - perhaps give them the code that enables to see the contents (IntroSurvey$age), in case they forgot how. 
* [x] When asking them to compute mean with na.rm=TRUE, we can add na.rm=1 and na.rm=T as other possible answers. This also applies to the question regarding psychology courses taken by the students (mean(IntroSurvey$psych_courses, na.rm=TRUE)).
* [x] Not sure what is the column that can answer this question: "What is the mean number of psychology classes taken by our participants?"
* [x] **REMOVED bc summary doesn't give you levels of character cols** Not sure students will be able to answer this question: "Enter a command that tells you how many participants are left-handed". Perhaps we can divide this to two stages, first tell them to write up the logical statement, and then tell them to add sum() before the statement to count the number of TRUE instances.

**Comment by monicathieu** [comment]
Upon reflection, I think we are teaching better ways of viewing summary statistics on character columns in assignment 2. For example, using `dplyr::count()` to show the number of values at various levels of a char column automatically "factor-ifies" the data under the hood to get around the fact that calling `summary()` on character vectors doesn't tell you the levels of the vector. As such, I think the move here is to shorten the assignment a little bit by removing the questions where we ask them to generate summary data on character columns.
